/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on Sep 23, 2012, 12:18:13 AM
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author Andy
 */
public class About extends javax.swing.JFrame {

    private String version = "RC4";
    
    /** Creates new form About */
    public About() {
        initComponents();
        
        showDialog();
        
        System.exit(0);
    }
    
    private void showDialog() {
        JOptionPane.showMessageDialog(this,
                                    "作者：Andy Liu\n部落格：meditationsilence.wordpress.com\n臉書：Liu Yan Ting\n版本：" + version,
                                    "關於 Millionaire",
                                    JOptionPane.INFORMATION_MESSAGE,
                                    new javax.swing.ImageIcon(getClass().getResource("/Misc/cc-BY-SA.png")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void show(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new About().setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
