package Interface;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingConstants;

public class Callout extends javax.swing.JDialog {
    final long CALLOUT_TIME = 30000;
    private javax.swing.Timer timer;

    public Callout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        centerScreen();
        
        initialize();
        
    }
    
    private void initialize() {

        final SimpleDateFormat sdf = new SimpleDateFormat("ss");

        setClock(sdf.format(new Date(CALLOUT_TIME)));

        int x = 0;
        
        ActionListener al = new ActionListener() {
            long x = CALLOUT_TIME - 1000;
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(x == 0) {
                     closeWindow();
                }
                setClock(sdf.format(new Date(x)));
                x-=1000;
            }
        };
        
        timer = new javax.swing.Timer(1000, al);
        timer.start();
    } 
    
    private void closeWindow() {
        this.dispose();
    }
    
    private void setClock(String input){
        countdown.setText("救援時間剩下 " + input + " 秒");
    }
    
    private void centerScreen() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - this.getSize().width)/2;
        int y = (dim.height - this.getSize().height)/2;
        this.setLocation(x, y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        countdown = new javax.swing.JLabel("countdown", SwingConstants.CENTER);
        earlyend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("危在旦夕");

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24));
        jLabel1.setText("好同學們");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24));
        jLabel2.setText("趕快拯救深陷苦難的同胞啊~");

        countdown.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        countdown.setText("救援時間剩下 ss 秒");

        earlyend.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        earlyend.setText("提前結束");
        earlyend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earlyendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(earlyend)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(countdown, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(countdown)
                .addGap(42, 42, 42)
                .addComponent(earlyend)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void earlyendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earlyendActionPerformed
        timer.stop();
        closeWindow();
    }//GEN-LAST:event_earlyendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void show(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Callout dialog = new Callout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countdown;
    private javax.swing.JButton earlyend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
